run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gosec
    - gocritic
    - unconvert
    - prealloc
    - exportloopref
    - goconst
    - bodyclose
    - noctx
    - wastedassign
    - unparam
    - nakedret
    - errorlint
    - exhaustive
    - nolintlint
    - whitespace
    - shadow

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  goimports:
    local-prefixes: github.com/seredavin/helmfile-validate
  gosec:
    severity: medium
    confidence: medium
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

issues:
  exclude-dirs:
    - vendor
    - vendor-stubs
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - gocritic
        - goconst
    - path: vendor
      linters:
        - all
    - path: vendor-stubs
      linters:
        - all
  max-issues-per-linter: 0
  max-same-issues: 0
